### ISSUE TITLE
Line numbers don't allow for newlines within tags

### ISSUE THREAD

**Issue by michaelhkay** [jindw/xmldom#145] opened 2016-01-05 11:37 UTC
Line numbers as reported using the Element.lineNumber property do not take account of line breaks occurring within start tags, for example with the input

```
<package xmlns="http://ns.saxonica.com/xslt/export"
         xmlns:fn="http://www.w3.org/2005/xpath-functions"
         xmlns:xs="http://www.w3.org/2001/XMLSchema"
         xmlns:vv="http://saxon.sf.net/generated-variable"
         version="20"
         packageVersion="1">
  <co id="0" binds="1">
</package>
```

the `<co>` element is reported as being on line 2.

**Comment by DotJoshJohnson** [comment] 2016-01-07 15:47
I've run into the same issue. It looks like the issue is with [this line](https://github.com/jindw/xmldom/blob/c033b1907c049ee10a9cc71133925480f03e7134/sax.js#L141) in [sax.js](https://github.com/jindw/xmldom/blob/c033b1907c049ee10a9cc71133925480f03e7134/sax.js). I commented the line out and everything seems to be working fine. I may submit a PR at some point, but I'm not familiar enough with all of the edge cases to be confident in doing so just yet. PR reviews don't seem to be very active anyway.

**Comment by DotJoshJohnson** [comment] 2016-01-07 21:03
Scratch that. This throws off the position of the node itself.

**Comment by jindw** [comment] 2016-01-13 11:19
fixed in latest version thanks

**Closed by jindw** 2016-01-13 11:19 UTC
